# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
