# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HomeScreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('bhk', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('usage', models.CharField(default=None, max_length=20)),
                ('date_added', models.DateField()),
                ('property_type', models.ForeignKey(db_column='PropertyType.id', on_delete=django.db.models.deletion.CASCADE, to='HomeScreen.PropertyType')),
            ],
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(db_column='PropertyTable.id', on_delete=django.db.models.deletion.CASCADE, to='Property.PropertyTable'),
        ),
    ]
