# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytable',
            name='bhk',
            field=models.CharField(max_length=10),
        ),
    ]
