# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_auto_20170901_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
