# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_auto_20170901_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytable',
            name='about_property',
            field=models.TextField(blank=True, null=True),
        ),
    ]
